INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('1','admin');
INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('2','user01');
INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('3','user02');
INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('4','user03');
INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('5','user04');
INSERT INTO TB_USER (USER_NO,USER_ID) VALUES('6','user05');

