INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD,USERNAME) VALUES('1','admin','admin','어드민');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD,USERNAME) VALUES('2','user01','user01','김유저1');
INSERT INTO USER_ENTITY_ROLES (USER_ENTITY_USER_NO,ROLES) VALUES('1','ROLE_ADMIN');
INSERT INTO USER_ENTITY_ROLES (USER_ENTITY_USER_NO,ROLES) VALUES('2','ROLE_USER');


