INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('1','admin','admin');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('2','user01','user01');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('3','user02','user02');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('4','user03','user03');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('5','user04','user04');
INSERT INTO TB_USER (USER_NO,USER_ID,PASSWORD) VALUES('6','user05','user05');

